"""Add update_changed_date col

Revision ID: 08bb2843c809
Revises: 553aeee7e7fe
Create Date: 2024-12-03 20:10:57.076670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bb2843c809'
down_revision = '553aeee7e7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_changed_date', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('update_changed_date')

    # ### end Alembic commands ###
