"""Add new col track

Revision ID: 14d6d30fb967
Revises: e29ec8736f23
Create Date: 2024-11-19 01:11:25.123316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d6d30fb967'
down_revision = 'e29ec8736f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('track')

    # ### end Alembic commands ###
