"""Add count_difference

Revision ID: 4cfff645584e
Revises: b6c668a1011c
Create Date: 2024-11-15 18:35:16.458797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfff645584e'
down_revision = 'b6c668a1011c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_difference', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.drop_column('count_difference')

    # ### end Alembic commands ###
