"""Add added date

Revision ID: 54b7172ae6f1
Revises: f250aad99737
Create Date: 2024-11-25 23:29:41.526232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b7172ae6f1'
down_revision = 'f250aad99737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('added_date')

    # ### end Alembic commands ###
