"""Add facebook changed date col

Revision ID: 553aeee7e7fe
Revises: 58fe13276125
Create Date: 2024-12-02 17:57:06.466370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553aeee7e7fe'
down_revision = '58fe13276125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_changed_date', sa.Date(), nullable=True))
        batch_op.drop_column('product_created_days_ago')
        batch_op.drop_column('domain_registration_date')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('creation_date_days_ago')
        batch_op.drop_column('product_created_date')
        batch_op.drop_column('div_start_date_days_ago')
        batch_op.drop_column('div_start_date')
        batch_op.drop_column('domain_registration_date_days_ago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_registration_date_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('div_start_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('div_start_date_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('product_created_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('creation_date_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('creation_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('domain_registration_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('product_created_days_ago', sa.INTEGER(), nullable=True))
        batch_op.drop_column('facebook_changed_date')

    # ### end Alembic commands ###
