"""added new 4 cols update to date

Revision ID: 58fe13276125
Revises: e859b85d835f
Create Date: 2024-11-26 01:21:56.032631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fe13276125'
down_revision = 'e859b85d835f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creative_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('faceboook_created_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('prod_created_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('domain_reg_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('domain_reg_date')
        batch_op.drop_column('prod_created_date')
        batch_op.drop_column('faceboook_created_date')
        batch_op.drop_column('creative_start_date')

    # ### end Alembic commands ###
