"""Add new columns

Revision ID: 6310b64c39ad
Revises: d557048a92b5
Create Date: 2024-11-17 04:43:52.919163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6310b64c39ad'
down_revision = 'd557048a92b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_count_history', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('count_difference', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('count_difference')
        batch_op.drop_column('result_count_history')

    # ### end Alembic commands ###
