"""Add new cols

Revision ID: 88498aedff10
Revises: 6310b64c39ad
Create Date: 2024-11-17 10:15:37.662452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88498aedff10'
down_revision = '6310b64c39ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('track_date_days_ago', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('track_date_days_ago')
        batch_op.drop_column('track_date')

    # ### end Alembic commands ###
