"""modify logdata

Revision ID: 89486947bb6d
Revises: 14d6d30fb967
Create Date: 2024-11-20 03:13:07.342652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89486947bb6d'
down_revision = '14d6d30fb967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('info', sa.String(length=500), nullable=True))
        batch_op.drop_column('keyword_number')
        batch_op.drop_column('loaded_results')
        batch_op.drop_column('available_results')
        batch_op.drop_column('keyword')
        batch_op.drop_column('keyword_database_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword_database_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('keyword', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('available_results', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('loaded_results', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('keyword_number', sa.INTEGER(), nullable=True))
        batch_op.drop_column('info')
        batch_op.drop_column('action')

    # ### end Alembic commands ###
