"""Add added_date and added_days_ago columns to URLData

Revision ID: b6c668a1011c
Revises: 
Create Date: 2024-11-11 20:57:58.144183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c668a1011c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('added_days_ago', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_data', schema=None) as batch_op:
        batch_op.drop_column('added_days_ago')
        batch_op.drop_column('added_date')

    # ### end Alembic commands ###
