"""Add new database and col

Revision ID: da99b14410b1
Revises: 4cfff645584e
Create Date: 2024-11-17 03:17:20.179514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da99b14410b1'
down_revision = '4cfff645584e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyword', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('div_href', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('div_library_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('div_start_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('div_start_date_days_ago', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('div_ads_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('facebook_about_page', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('page_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('page_ads_link', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('creation_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('creation_date_days_ago', sa.Integer(), nullable=True))
        batch_op.alter_column('ads_library_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('registration_date')
        batch_op.drop_column('created_at_date')
        batch_op.drop_column('time_taken')
        batch_op.drop_column('count_difference')
        batch_op.drop_column('added_date')
        batch_op.drop_column('url')
        batch_op.drop_column('whois_url')
        batch_op.drop_column('product_name')
        batch_op.drop_column('domain')
        batch_op.drop_column('created_days_ago')
        batch_op.drop_column('registration_days_ago')
        batch_op.drop_column('result_count_history')
        batch_op.drop_column('added_days_ago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('result_count_history', sa.VARCHAR(length=400), nullable=True))
        batch_op.add_column(sa.Column('registration_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('whois_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('added_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('count_difference', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('time_taken', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('ads_library_url',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('creation_date_days_ago')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('page_ads_link')
        batch_op.drop_column('page_id')
        batch_op.drop_column('facebook_about_page')
        batch_op.drop_column('div_ads_count')
        batch_op.drop_column('div_start_date_days_ago')
        batch_op.drop_column('div_start_date')
        batch_op.drop_column('div_library_id')
        batch_op.drop_column('div_href')
        batch_op.drop_column('keyword')

    # ### end Alembic commands ###
