"""remove track date and days ago

Revision ID: e859b85d835f
Revises: 54b7172ae6f1
Create Date: 2024-11-26 01:01:42.101498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e859b85d835f'
down_revision = '54b7172ae6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('track_date')
        batch_op.drop_column('track_date_days_ago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_date_days_ago', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('track_date', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
