"""Add new column

Revision ID: ebbe18bea392
Revises: 89486947bb6d
Create Date: 2024-11-22 01:05:21.396066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbe18bea392'
down_revision = '89486947bb6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_registration_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('domain_registration_date_days_ago', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('domain_registration_date_days_ago')
        batch_op.drop_column('domain_registration_date')

    # ### end Alembic commands ###
