"""Add last update

Revision ID: f250aad99737
Revises: 4adace76a7cf
Create Date: 2024-11-25 18:36:13.347371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f250aad99737'
down_revision = '4adace76a7cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads_data', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
